---
layout: post
title:  "go学习第四篇(常用关键字)"
date:   2018-09-01 00:06:05
categories: go
tags: go基础
excerpt: go
---

* content
{:toc}


#### defer

用于资源释放，会在函数返回之前调用。如果有多个defer表达式，调用顺序类似于栈，越后面的defer表达式越先被调用。

注意：defer表达式可能会在设置函数返回值之后，在返回到调用函数之前，修改返回值，使最终的函数返回值与你想象的不一致。


- defer表达式中变量的值在defer表达式被定义时就已经明确

```

package main

import (
	"fmt"
)

func main() {
	i := 0
	defer fmt.Println(i)
	i++
	return
}


```

上面的这段代码，defer表达式中用到了i这个变量，i在初始化之后的值为0，接着程序执行到defer表达式这一行，表达式所用到的i的值就为0了，接着，表达式被放入list，等待在return的时候被调用。所以，后面尽管有一个i++语句，仍然不能改变表达式 fmt.Println(i)的结果。

所以，程序运行结束的时候，输出的结果是0而不是1。

- defer表达式的调用顺序是按照先进后出的方式


#### panic&recover

-  panic 是用来表示非常严重的不可恢复的错误的。假如函数F中书写了panic语句，会终止其后要执行的代码，在panic所在函数F内如果存在要执行的defer函数列表，按照defer的逆序执行。返回函数F的调用者G，在G中，调用函数F语句之后的代码不会执行，假如函数G中存在要执行的defer函数列表，按照defer的逆序执行，直到goroutine整个退出，并报告错误

```
package main

import (
	"fmt"
)

func writeLog() {
	fmt.Println("收尾工作")
}

func main() {

	fmt.Println("执行第一次")
	fmt.Println("执行第二次")
	defer writeLog()
	panic("阻止继续执行")
	defer writeLog()

	fmt.Println("执行第三次")

}


```

结果：

```
panic: 阻止继续执行

goroutine 1 [running]:
main.main()
	/Users/nivellefu/golearn-gotype/learn0901926.go/valueTest.go:16 +0xd9
执行第一次
执行第二次
收尾工作

```


- 用来控制一个goroutine的panicking行为，捕获panic，从而影响应用的行为，也可以可以获取通过panic传递的error。

```
package main

import (
	"fmt"
)

func main() {

	fmt.Println("执行第一次")
	fmt.Println("执行第二次")
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("---error----", err)
		}
	}()
	panic("阻止继续执行")
	//defer writeLog()

	fmt.Println("执行第三次")

}


```

结果：

```

执行第一次
执行第二次
---error---- 阻止继续执行
成功: 进程退出代码 0.


```
